config/routes.rb
Rails.application.routes.draw do
  root "members#index"
  get 'tube_vids', to: 'tube_vids#index'
  post "dl", to: "documents#download"
  get '@admin_entry', to: "members#admin_entry"
  post "admin_login", to: "members#admin_login"
  get "@admin_logout", to: "members#admin_logout"
  get 'members', to: 'members#index'
  get 'documents', to: 'documents#index'
  get 'tube_vidss', to: 'tube_vidss#index'
  get 'manual', to: 'members#manual'
  namespace :ceb9458d5364668953b05327205aa8af do
    get 'manual', to: 'members#manual'
    root "members#index"
    get 'get_logs', to: 'members#get_logs'
    resources :tags
    resources :members, except: [:destroy, :new, :edit]
    post 'del/:id', to: 'members#destroy'
    post 'dead_tube', to: 'tube_vids#destroy'
    post 'tag_del', to: 'documents#tag_del'
    post 'tag_create', to: 'documents#tag_create'
    post 'tag_toggle', to: 'documents#tag_toggle'
    resources :documents, except: [:new,:show,:edit,:create, :destroy]
    post "upload", to: "documents#upload"
    resources :tube_vids, except: [:show,:new,:edit]
    post "rm", to: 'documents#remove'
    patch 'rename', to: 'documents#rename'
    patch 'rename_tag', to: 'documents#rename_tag'
    post 'change_password', to: 'members#change_password'
    patch 'alter_order', to: 'members#alter_order'
  end
end

app/models/tube_vid.rb
class TubeVid < ApplicationRecord
  validates_uniqueness_of :vid
  validates_presence_of :vid, :title
  after_save :recount
  after_destroy :recount

  def recount
    Counter.update(name: 'TubeVid', count: TubeVid.count)
  end
end

app/controllers/ceb9458d5364668953b05327205aa8af/tube_vids_controller.rb
class Ceb9458d5364668953b05327205aa8af::TubeVidsController < ApplicationController
  before_action :set_tube_vid, only:[:destroy, :update]
  before_action :member_validate

  def index
    unless (@tube_vids = Rails.cache.fetch(:tube_vids))
      @tube_vids = TubeVid.order('created_at desc')
      Rails.cache.write(:tube_vids, @tube_vids)
    end
  end

  def create
    str = %x(curl 'https://www.youtube.com/watch?v=#{tube_param['pid']}')
    html = Nokogiri::HTML(str)
    title = html.at("#eow-title").attr('title')
    puts title
    tv = TubeVid.new(title: title,vid: tube_param['pid'])
    if tv.save
      Rails.cache.delete :tube_vids
      Rails.cache.delete :counters
      regist_record("新增了YouTube影片",
                    "#{tv.title}")
      @tv_title = tv.title
      @tv_id = tv.id
      @tv_vid = tv.vid
      pid = tube_param['pid']
      thumbnail_url = "https://img.youtube.com/vi/#{pid}/hqdefault.jpg"
    else
      head 500
    end
  end

  def destroy
    @victim = if @tube_vid.title.size>23
                @tube_vid.title[0,8]+". . ."+@tube_vid.title[-8,8]
              else
                @tube_vid.title
              end
    @tube_vid.destroy
    Rails.cache.delete :tube_vids
    Rails.cache.delete :counters
    regist_record("刪除了YouTube影片",
                  "#{@tube_vid.title}")
  end

  def update
    origin = @tube_vid.title
    @tube_vid.update(title: tube_param['title'])
    Rails.cache.delete :tube_vids
    regist_record("重新命名了YouTube影片",
                  "#{origin} -> #{@tube_vid.title}")
    @tube_title = @tube_vid.title
  end

  private

  def set_tube_vid
    @tube_vid = TubeVid.find(params[:id])
  end

  def tube_param
    params.permit(:pid, :title)
  end
end

app/controllers/tube_vids_controller.rb
class TubeVidsController < ApplicationController
  def index
    unless (@tube_vids = Rails.cache.fetch(:tube_vids))
      @tube_vids = TubeVid.order('created_at desc')
      Rails.cache.write(:tube_vids, @tube_vids)
    end
  end
end

app/helpers/ceb9458d5364668953b05327205aa8af/tube_vids_helper.rb
module Ceb9458d5364668953b05327205aa8af::TubeVidsHelper
end

app/helpers/tube_vids_helper.rb
module TubeVidsHelper
end

app/views/tube_vids/_form.html.erb
<%= form_for(tube_vid) do |f| %>
  <% if tube_vid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tube_vid.errors.count, "error") %> prohibited this tube_vid from being saved:</h2>

      <ul>
      <% tube_vid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tube_vids/edit.html.erb
<h1>Editing Tube Vid</h1>

<%= render 'form', tube_vid: @tube_vid %>

<%= link_to 'Show', @tube_vid %> |
<%= link_to 'Back', tube_vids_path %>

app/views/tube_vids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tube Vids</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tube_vids.each do |tube_vid| %>
      <tr>
        <td><%= link_to 'Show', tube_vid %></td>
        <td><%= link_to 'Edit', edit_tube_vid_path(tube_vid) %></td>
        <td><%= link_to 'Destroy', tube_vid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tube Vid', new_tube_vid_path %>

app/views/tube_vids/new.html.erb
<h1>New Tube Vid</h1>

<%= render 'form', tube_vid: @tube_vid %>

<%= link_to 'Back', tube_vids_path %>

app/views/tube_vids/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tube_vid_path(@tube_vid) %> |
<%= link_to 'Back', tube_vids_path %>