config/routes.rb
Rails.application.routes.draw do
  root "members#index"
  get 'tube_vids', to: 'tube_vids#index'
  post "dl", to: "documents#download"
  get '@admin_entry', to: "members#admin_entry"
  post "admin_login", to: "members#admin_login"
  get "@admin_logout", to: "members#admin_logout"
  get 'members', to: 'members#index'
  get 'documents', to: 'documents#index'
  get 'tube_vidss', to: 'tube_vidss#index'
  get 'manual', to: 'members#manual'
  namespace :ceb9458d5364668953b05327205aa8af do
    get 'manual', to: 'members#manual'
    root "members#index"
    get 'get_logs', to: 'members#get_logs'
    resources :tags
    resources :members, except: [:destroy, :new, :edit]
    post 'del/:id', to: 'members#destroy'
    post 'dead_tube', to: 'tube_vids#destroy'
    post 'tag_del', to: 'documents#tag_del'
    post 'tag_create', to: 'documents#tag_create'
    post 'tag_toggle', to: 'documents#tag_toggle'
    resources :documents, except: [:new,:show,:edit,:create, :destroy]
    post "upload", to: "documents#upload"
    resources :tube_vids, except: [:show,:new,:edit]
    post "rm", to: 'documents#remove'
    patch 'rename', to: 'documents#rename'
    patch 'rename_tag', to: 'documents#rename_tag'
    post 'change_password', to: 'members#change_password'
    patch 'alter_order', to: 'members#alter_order'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_docships, dependent: :destroy
  has_many :documents, through: :tag_docships
end

app/helpers/ceb9458d5364668953b05327205aa8af/tags_helper.rb
module Ceb9458d5364668953b05327205aa8af::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>