config/routes.rb
Rails.application.routes.draw do
  root "members#index"
  get 'tube_vids', to: 'tube_vids#index'
  post "dl", to: "documents#download"
  get '@admin_entry', to: "members#admin_entry"
  post "admin_login", to: "members#admin_login"
  get "@admin_logout", to: "members#admin_logout"
  get 'members', to: 'members#index'
  get 'documents', to: 'documents#index'
  get 'tube_vidss', to: 'tube_vidss#index'
  get 'manual', to: 'members#manual'
  namespace :ceb9458d5364668953b05327205aa8af do
    get 'manual', to: 'members#manual'
    root "members#index"
    get 'get_logs', to: 'members#get_logs'
    resources :tags
    resources :members, except: [:destroy, :new, :edit]
    post 'del/:id', to: 'members#destroy'
    post 'dead_tube', to: 'tube_vids#destroy'
    post 'tag_del', to: 'documents#tag_del'
    post 'tag_create', to: 'documents#tag_create'
    post 'tag_toggle', to: 'documents#tag_toggle'
    resources :documents, except: [:new,:show,:edit,:create, :destroy]
    post "upload", to: "documents#upload"
    resources :tube_vids, except: [:show,:new,:edit]
    post "rm", to: 'documents#remove'
    patch 'rename', to: 'documents#rename'
    patch 'rename_tag', to: 'documents#rename_tag'
    post 'change_password', to: 'members#change_password'
    patch 'alter_order', to: 'members#alter_order'
  end
end

app/models/member.rb
class Member < ApplicationRecord
  validates_presence_of :name, :title, :resp, :ext, :mail
  validates_uniqueness_of :mail, :ext
  before_save :n2br
  after_save :recount
  after_destroy :recount

  def n2br
    self.resp = self.resp.gsub("\n","<br>")
  end

  def recount
    Counter.update(name: 'Member', count: Member.count)
  end

  # 刪除成員時，將display_order大於自己的成員都順序-1
  # base(int) = 目標的原先位置(刪除)或插入位置(插入)
  def self.d_alter_order base
    Member.transaction do
      Member.where("display_order > #{base}").order("display_order ASC").update_all('display_order = display_order - 1')
    end
  end

  # 插入時，插入位置以後的都+1(先將自己設定爲-1避免重複)
  def i_alter_order change_amount
    begin
      Member.transaction do
        origin_order = self.display_order
        self.update(display_order: -1)
        if change_amount > 0 # 向下
          Member.where("display_order > ? and display_order < ?", origin_order, origin_order + change_amount + 1).update_all("display_order=display_order-1")
        else # 向上
          Member.where("display_order < ? and display_order > ?", origin_order, origin_order + change_amount - 1).update_all("display_order=display_order+1")
        end
        self.update(display_order: origin_order + change_amount)
        return true
      end
    rescue
      return false
    end
  end
end

app/controllers/ceb9458d5364668953b05327205aa8af/members_controller.rb
class Ceb9458d5364668953b05327205aa8af::MembersController < ApplicationController
  before_action :set_member, only: [:destroy, :update, :alter_order]
  before_action :member_validate
  before_action :ie_go_die, if: :is_ie?

  def index
    unless (@members = Rails.cache.fetch(:members))
      @members = Member.order('display_order ASC')
      Rails.cache.write(:members, @members)
    end

    unless (@counters = Rails.cache.fetch(:counters))
      @counters = Counter.pluck(:count)
      Rails.cache.write(:counters, @counters)
    end

    %x(bash #{Rails.root}/delete_broken_tmp.sh)
  end

  def manual
    markdown_content = File.read(Rails.root.join('b-manual.md'))
    render html: Kramdown::Document.new(markdown_content).to_html.html_safe
  end

  def get_logs
    @logs = Register.all.reverse
  end

  def create
    new_member = Member.new member_param
    new_member.display_order = Member.count + 1
    unless new_member.save
      head 500
    end
    Rails.cache.delete :counters
    Rails.cache.delete :members
    @new_member = new_member
    regist_record("新增了 成員資料",
                 "#{@new_member.name}(#{@new_member.ext})")
  end

  def destroy
    
    target = @member.destroy
    Rails.cache.delete :counters
    Rails.cache.delete :members
    @victim = target.name
    Member.d_alter_order target.display_order
    regist_record("刪除了 成員資料",
                 "#{target.name}(#{target.ext})")
  end

  def update
    origin = {name: @member.name, ext: @member.ext}
    if session[:admin] == @member.mail
      unless @member.update member_param
        head 500
      end
      session[:admin] = @member.mail
      Rails.cache.delete :members
      regist_record("更新了 成員資料",
                   "自己")
    else
      unless @member.update member_param
        head 500
      end
      Rails.cache.delete :members
      regist_record("更新了 成員資料",
                   "#{origin[:name]}(#{origin[:ext]})")
    end
    if (target_tag = Tag.find_by_name "由#{origin[:name]}上傳")
      target_tag.update(name: "由#{@member.name}上傳")
    end
  end

  def alter_order
    unless @member.i_alter_order(params[:change_amount])
      head 500
    end
  end

  def change_password
    if params[:password] == params[:re_password]
      if @target_member.update(passwd: Digest::SHA1::hexdigest(params[:password]))
        head 200
      else
        head 500
      end
    end
  end

  private

  def member_param
    params.permit(:name, :title, :resp, :ext, :mail)
  end

  def set_member
    @member = Member.find(params[:id])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  layout "entry", only: [:admin_entry]

  def index
    unless (@members = Rails.cache.fetch(:members))
      @members = Member.order('display_order ASC')
      Rails.cache.write(:members, @members)
    end

    unless (@counters = Rails.cache.fetch(:counters))
      @counters = Counter.pluck(:count)
    end

    %x(bash #{Rails.root}/delete_broken_tmp.sh)
  end

  def manual
    markdown_content = File.read(Rails.root.join('f-manual.md'))
    render html: Kramdown::Document.new(markdown_content).to_html.html_safe
  end

  def admin_entry
    if Member.find_by_mail session[:admin]
      redirect_to '/ceb9458d5364668953b05327205aa8af'
    end
  end

  def admin_login
    acc = params[:account]
    pw = params[:password]
    if ( targetMember = Member.find_by_ext(acc) )
      if Digest::SHA1::hexdigest(pw) ==  targetMember.passwd
        session[:admin] = targetMember.mail
        redirect_to '/ceb9458d5364668953b05327205aa8af'
      else
        redirect_to '/@admin_entry'
      end
    else
      redirect_to '/@admin_entry'
    end
  end

  def admin_logout
    session[:admin].clear
    redirect_to '/'
  end
end

app/helpers/ceb9458d5364668953b05327205aa8af/members_helper.rb
module Ceb9458d5364668953b05327205aa8af::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_doc_list.html.erb
<div v-for="doc in docs" :data-title="doc.title" :data-tags="doc.taggedWith" :data-id="doc.id" class="file-container" @mousedown="select(0,$event)">
  <svg class="doc-icon" @mousedown="select(1,$event)">
    <use v-bind="{ 'xlink:href': doc.iconUrl  }" @mousedown="select(2,$event)"></use>
  </svg>
  <div class="icon-mask"></div>
  <div class="doc-name-tag" @mousedown="select(1,$event)">
    {{doc.title + doc.ext}}
  </div>
</div>

app/views/members/_explorer_menu.html.erb
<div id="explorer-menu" class="z2">
  <div id="act-dl" class="explorer-action" @mouseenter="showTooltip('下載單個檔案或打包多個檔案下載')" @mouseleave="hideTooltip" @click="downloadFile">
    下載
  </div>
</div>

app/views/members/_footer.html.erb
<div id="footer">
  <svg id="manual-btn">
    <use xlink:href='/assets/icon/icons.svg#qmark'></use>
  </svg>
</div>

app/views/members/_member_table_cell.html.erb
<div id="member-list">
  <member :name="member.name" :title="member.title" :resp="member.resp" :ext="member.ext" :mail="member.mail" v-for="member in members " :key="member.id"></member>
</div>

app/views/members/_menu.html.erb
<div id="menu">
  <svg class="menu-option now" data-order=0>
    <use xlink:href="/assets/icon/icons.svg#member"></use>
  </svg>
  <span id="memb-count" class="data-count"><%= @counters[0]%></span>
  <svg class="menu-option" data-order=1>
    <use data-target="files-content" xlink:href="/assets/icon/icons.svg#files"></use>
  </svg>
    <span id="doc-count" class="data-count"><%= @counters[1]%></span>
  <svg class="menu-option" data-order=2>
    <use data-target="tube-content" xlink:href="/assets/icon/icons.svg#youtube"></use>
  </svg>
    <span id="tube-count" class="data-count"><%= @counters[2]%></span>
  <svg id="logo">
    <use data-target="tube-content" xlink:href="/assets/icon/icons.svg#logo"></use>
  </svg>
  <svg id="site-name" viewBox="0 0 2000 200">
    <use xlink:href="/assets/icon/icons.svg#site-name"></use>
  </svg>
</div>

app/views/members/_sys_msg.html.erb
<div id="sys-msg" class="z3">
  <svg id="info-icon">
    <use xlink:href="/assets/icon/icons.svg#info-icon"></use>
  </svg>
  <span></span>
</div>

app/views/members/_tag_filters.html.erb
<div class="tag-filter" v-for="tag in tags" :data-tag-id="tag.id" :data-doc-ids="tag.docIds" :data-next-tags="tag.docIds" @click="toggleFilter($event)" v-if="tag.docCount > 0">
  <span class="tag-filter-name">{{tag.name}}</span>
  <span class="tag-filter-count">{{tag.docCount}}</span>
</div>

app/views/members/_tv_list.html.erb
<div id="tv-list">
  <div class="tv-container" :data-id="tv.id" :data-title="tv.title" v-for="tv in tubeVids">
    <span class="tv-title" :title="tv.title">
      {{tv.title}}
    </span>
    <div class="a-tv" :style="{'background-image': 'url(\'https://img.youtube.com/vi/'+tv.vid+'/mqdefault.jpg\')'}" @click="playTube(tv.vid)" @mouseover="showTooltip('播放「'+tv.title+'」')" @mouseleave="hideTooltip">
    </div>
  </div>
</div>
<div id="tube-page-left" class="change-page" @mouseenter="showTooltip('YouTube列表 上一頁')" @mouseleave="hideTooltip" @click="prevPage">＜</div>
<div id="tube-page-right" class="change-page" @mouseenter="showTooltip('YouTube列表 下一頁')" @mouseleave="hideTooltip" @click="nextPage">＞</div>

app/views/members/_youtube_player.html.erb
<iframe id="tube-viewer" class="z2" src="" frameborder="0"></iframe>
<svg id="close-tube" class="z2" viewBox="0 0 80 80">
  <line x1="20" y1="20" x2="60" y2="60"></line>
  <line x1="60" y1="20" x2="20" y2="60"></line>
</svg>

app/views/members/admin_entry.html.erb
<div id="login-form">
  <%= form_tag "/admin_login", method: "POST" do %>
      <%= text_field :account, nil, id: 'entry-account', class: 'entry-field', placeholder: '帳號(分機)', required: true %>
      <%= password_field_tag :password, nil, id: 'entry-password',class: 'entry-field', placeholder: '密碼', required: true %>
      <%= submit_tag "登入" %>
  <% end %>
</div>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<div id="root-content" class="first">
  <%= render 'loading' %>
  <%= render 'menu' %>
  <div id="tooltip"></div>
  <%= render 'footer' %>
  <div id="members-content" class="main-content current z1">
    <div class="cTable z1">
      <%= render 'member_table_head' %>
      <%= render 'member_table_cell' %>
    </div>
  </div>
  <div id="files-content" class="main-content">
    <%= form_tag '/dl', authenticity_token: true, id: 'download-form' do %>
      <%= hidden_field_tag 'file_id' %>
      <%= hidden_field_tag 'download_mode'%>
    <% end %>
    <div id="tag-zone">
      <%= render 'tag_filters' %>
    </div>
    <div id="file-explorer" tabindex="1" @keydown.f2="editFileTitle" @keydown.delete="removeFile" @keydown.enter="downloadFile">
      <div id="select-zone"></div>
      <%= render 'explorer_menu' %>
      <%= render 'doc_list' %>
    </div>
    <div id="doc-page-left" class="change-page" @mouseenter="showTooltip('檔案列表 上一頁')" @mouseleave="hideTooltip" @click="prevPage">＜</div>
    <div id="doc-page-right" class="change-page" @mouseenter="showTooltip('檔案列表 下一頁')" @mouseleave="hideTooltip" @click="nextPage">＞</div>
  </div>
  <div id="tube-content" class="main-content">
    <%= render 'tv_list' %>
  </div>
  <%= render 'sys_msg' %>
  <%= render 'youtube_player' %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>